
   - name: installling nginx
     ansible.builtin.package:
       name: nginx
       state: present

   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes 
   - name: importing tasks
     ansible.builtin.import_role:
        name: common
        tasks_from: main
  

  

   - name: Copy the file to the remote server
     ansible.builtin.template:
        src: expense.conf.j2  # Path to the local file on the control machine
        dest:  /etc/nginx/default.d/expense.conf  
     notify: restart nginx      

   