
   - name: installling nginx
     ansible.builtin.package:
       name: nginx
       state: present

   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes 

   - name: ansible module to remove directory
     ansible.builtin.file:
      path: rm -rf /usr/share/nginx/html/*
      state: absent     

   - name: ansible module to remove directory
     ansible.builtin.file:
      path:  /usr/share/nginx/html
      state: directory   

   - name: Download code (e.g., a tarball or zip file)
     ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip # URL to the code
        dest: /tmp/frontend.zip  #    


   -  name: Extract code to destination directory
      ansible.builtin.unarchive:
        src:  /tmp/frontend.zip     # Path to the archive on the control machine or remote host
        dest:    /usr/share/nginx/html              # Destination directory on the remote host
        remote_src: yes  

   - name: Copy the file to the remote server
     ansible.builtin.template:
        src: expense.conf.j2  # Path to the local file on the control machine
        dest:  /etc/nginx/default.d/expense.conf     

   - name: ansible module to restart the service
     ansible.builtin.service:
       name: nginx
       state: restarted           