 - name: Ensure the directory /opt/expense exists
   ansible.builtin.file:
        path: "{{app_location}}"   # The directory you want to create
        state: absent 
   ignore_errors: true    

 
 
 - name: Ensure the directory /opt/expense exists
   ansible.builtin.file:
      path: "{{ app_location}}"    # The directory you want to create
      state: directory  


 - name: Download code (e.g., a tarball or zip file)
   ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip # URL to the code
        dest: /tmp/{{component}}.zip  #    

 - name: Unzip the file and overwrite
   ansible.builtin.unarchive:
        src:  /tmp/{{component}}.zip
        dest: "{{app_location}}"
        remote_src: yes    